Repository yuca-live/yuca_pulso, pull requests merged in 2022-03, with the labels that each got.

#15 added more icons
  lib/icons/yuca_icons.dart
  lib/typography/fonts/YucaIcons.ttf
Labels: enhancement

#16 Yuca Tile
  lib/widgets/widgets.dart
  lib/widgets/yuca_tile.dart
Labels: enhancement

#23 create toggle
  lib/widgets/widgets.dart
  lib/widgets/yuca_toggle.dart
Labels: enhancement

#24 Refactor: Yuca alert message stateless
  example/lib/screens/alert_message_screen.dart
  lib/widgets/yuca_alert_message.dart
  lib/widgets/yuca_toggle.dart
Labels: documentation

#25 fix: assert validation
  lib/widgets/yuca_alert_message.dart
Labels: bug
